version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8003:8003"
    command: python manage.py runserver 0.0.0.0:8003

volumes:
  static-data: