# Generated by Django 4.2.11 on 2024-04-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('parameter', models.CharField(blank=True, default='', max_length=254)),
                ('updated_Date', models.DateTimeField(auto_now=True)),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
