# Generated by Django 4.2.11 on 2024-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='This is variable of the setting.', max_length=254, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=254, verbose_name='Description')),
                ('file', models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Image')),
                ('updated_Date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_Date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Image Setting',
                'verbose_name_plural': 'Image Settings',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'ordering': ['name'], 'verbose_name': 'General Setting', 'verbose_name_plural': 'General Settings'},
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='created_Date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of the setting', max_length=254, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Name of the setting', max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='parameter',
            field=models.CharField(blank=True, default='', help_text='Parameter of the setting', max_length=254, verbose_name='Parameter'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='updated_Date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
