# Generated by Django 4.2.11 on 2024-04-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSettings',
            new_name='GeneralSetting',
        ),
    ]
