# Generated by Django 4.2.11 on 2024-04-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_document_file_alter_imagesetting_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='parameter',
            field=models.CharField(blank=True, default='', help_text='Parameter of the setting', max_length=1024, verbose_name='Parameter'),
        ),
    ]
