# Generated by Django 4.2.11 on 2024-06-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_generalsetting_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('devops', 'DevOps'), ('other', 'Other')], default='backend', max_length=20),
        ),
    ]
