# Generated by Django 5.2.10 on 2026-02-06 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_skill_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='documents/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Name of the setting', max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='parameter',
            field=models.TextField(blank=True, default='', help_text='Parameter of the setting', max_length=1024, verbose_name='Parameter'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to='image_settings/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='This is variable of the setting.', max_length=254, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ('order', 'name'),
                'indexes': [models.Index(fields=['slug'], name='core_projec_slug_1555cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Short Description')),
                ('content', models.TextField(blank=True, verbose_name='Detailed Content (Markdown)')),
                ('featured_image', models.ImageField(blank=True, upload_to='projects/', verbose_name='Featured Image')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('live_url', models.URLField(blank=True, verbose_name='Live Demo URL')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated list of technologies (e.g., Django, React, PostgreSQL)', max_length=500)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Project')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projectcategory')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('order', '-created_date'),
                'indexes': [models.Index(fields=['slug'], name='core_projec_slug_fe29bd_idx'), models.Index(fields=['is_published', 'order'], name='core_projec_is_publ_497c54_idx')],
            },
        ),
    ]
