# Generated by Django 5.2.10 on 2026-02-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_document_file_alter_generalsetting_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('medium', 'Medium'), ('devto', 'Dev.to'), ('kaggle', 'Kaggle'), ('hackerrank', 'HackerRank'), ('leetcode', 'LeetCode'), ('codepen', 'CodePen'), ('stackoverflow', 'Stack Overflow'), ('reddit', 'Reddit'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('website', 'Personal Website'), ('other', 'Other')], default='other', help_text='Select social media platform', max_length=50, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Technology/skill name (e.g., Python, Django, Docker)', max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Leave blank to use default platform icon', max_length=254, verbose_name='Custom Icon (Optional)'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.URLField(blank=True, default='', help_text='Full URL to your profile', max_length=254, verbose_name='Link'),
        ),
    ]
