# Generated by Django 5.2.10 on 2026-02-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_date'], name='contact_mes_created_409f49_idx'),
        ),
    ]
