# Generated by Django 4.2.11 on 2024-04-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='blog_img/', verbose_name='Image'),
        ),
    ]
