# Generated by Django 5.2.10 on 2026-02-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag_post_improvements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_publish_a3f863_idx',
            old_name='blog_post_publish_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_slug_cdb902_idx',
            old_name='blog_post_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_status_02ce19_idx',
            old_name='blog_post_status_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary for listing pages and meta description', max_length=500, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image for the post', upload_to='blog_img/', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 characters)', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Auto-generated from title if left blank', max_length=250, unique=True, verbose_name='URL Slug'),
        ),
    ]
